import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/context/CartContext";
import { AppProvider } from "@/context/AppContext";
import { VoiceProvider } from "@/context/VoiceContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <AppProvider>
          <CartProvider>
            <VoiceProvider>
              {children}
            </VoiceProvider>
          </CartProvider>
        </AppProvider>
      </body>
    </html>
  );
}
